### ISSUE TITLE
🎲 2020-09-16-Meeting

### ISSUE THREAD

**Issue by Hansanghyeon** [hapas-io/hyupup#11]
**⏰ 이 회의록은 2020-09-16 에 정리될 예정입니다!**

### TODO
- [x] Slack 정기회의용 채널생성
- [x] 캘린더 일정 생성

### 멤버
역활   | 성명
------| ---
마스터  | @Hansanghyeon 
멤버   | @youngroklee323

**Comment by Hansanghyeon** [comment]
시작하기전 저번주 남은 Quest

### Quest
@youngroklee323 
- [ ] 삼멤 하나의 UI가 완료되면 UI관련된 내용 적어서 [Link 저장소](https://github.com/hapas-io/hyupup-storybook/issues) 이슈 생성

@Hansanghyeon 
- [ ] 삼멤 UI 나오기전에 [키오스크 UI](https://xd.adobe.com/view/5028e134-9d45-4f68-b691-b4746f91727a-057b/screen/9d10b08a-1344-4dc5-9425-0f6c52f6cded) 참고해서 UI 이슈 제작

**Comment by Hansanghyeon** [comment]
삼멤에서 UI에서 원래 동물을 타겟팅한 감성 UI를 타겟에서 서로 소통할수있는 아이스브레킹으로 전환한 UI가 만들어질 것이다.
