### ISSUE TITLE
🎲 2020-09-23-Meeting

### ISSUE THREAD

**Issue by youngroklee323** [hapas-io/hyupup#12]
**⏰ 이 회의록은 2020-09-24 에 정리될 예정입니다!**

### TODO
- [x] Slack 정기회의용 채널생성
- [x] 캘린더 일정 생성
- [x] [회의록 목록](https://github.com/hapas-io/hyupup/wiki) 추가

### 멤버
역할   | 성명
------| ---
마스터  | @youngroklee323 
멤버   | @Hansanghyeon

**Comment by youngroklee323** [comment]
이 소프트웨어의 목적을 잘 보여주면 될듯.
Zoom과 행아웃은 회의관련으로 광고를 내듯이

소통중심의 ui와 회의 관련 ui의 경계를 무너뜨리는 액티비티를 잘 보여줘야한다
쥐뿔도없지만 자소서 잘 쓰는 그런 자세가 필요하다!

경계를 무너뜨렸다는 점을 잘 보여주고, 그로인해 얻는 이득도 잘 보여주면 좋을듯하다.

5페이지는 기승전결을 위한 장치가 아닌가? 기를 늘리든 승을 늘리든

---
샤워할때 다음곡으로 넘기고싶은데 그럴수가없음.
운전할때 다음곡으로 넘기고 싶음
내가 무언가를 하고있을때, 어드바이스를 할 수 있는 서비스
예) 의사가 수술을할때, 로봇에게 눈빛이나 제스쳐로 제어

랜덤재생같은 특정 제스쳐는 어떻게?

구글글래스는 AR정점같다.
- 성능대비 미려하게 만들수없다. 성능과 디자인을 모두 성취할수없는 하드웨어적인 한계가 있음

애플워치가 파이를 넓히는 이유는, 애플워치라는 신개념 서비스를 만들었는데, 파이가 작으면 이득을 낼 순 없으니, 지속적으로 파이를 넓히려는 것.

AR서비스는 컨텐츠가 먼저 선두로 끌어야함
