### ISSUE TITLE
🎲 YYYY-MM-DD-Meeting

### ISSUE THREAD

**Issue by Hansanghyeon** [hapas-io/hyupup#13]
**⏰ 이 회의록은 YYYY-MM-DD 에 정리될 예정입니다!**

### TODO
- [ ] Slack 정기회의용 채널생성
- [ ] 캘린더 일정 생성
- [ ] [회의록 목록](https://github.com/hapas-io/hyupup/wiki) 추가

### 멤버
역할   | 성명
------| ---
마스터  | @Hansanghyeon 
멤버   | @youngroklee323
